# Change these first
owner: Jarvis
repo: Jarvis-Health-Check 

sites:
sites:
  - name: TestEnv
    url: https://it.wikipedia.org/wiki/Cartoon_Network
  - name: TestEnv2
    url: https://chatgpt.com
  - name: TestEnv3
    url: https://www.treccani.it/enciclopedia/musica/

    url: https://it.wikipedia.org/wiki/Cartoon_Network
