# Change these first
owner: Jarvis
repo: Jarvis-Health-Check 

sites:
sites:
  - name: TestEnv
    url: https://it.wikipedia.org/wiki/Cartoon_Network
  - name: TestEnv2
    url: https://chatgpt.com
  - name: TestEnv3
    url: https://www.treccani.it/enciclopedia/musica/
  - name: TestEnv3
    url: https://learn.microsoft.com/it-it/aspnet/core/razor-pages/?view=aspnetcore-9.0&tabs=visual-studio

    url: https://it.wikipedia.org/wiki/Cartoon_Network
