name: Update Sites from API

on:
  schedule:
    - cron: '*/6 * * * *'  # Ogni minuto
  workflow_dispatch:       # Per avvio manuale

jobs:
  update-sites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Call API to get environments
        run: |
          curl -ks https://6865cac489803950dbb0478b.mockapi.io/envs > sites.json

      - name: Generate new sites YAML block
        run: |
          jq -r '.[] | "  - name: \(.name)\n    url: \(.url)"' sites.json > new_sites_block.yml

      - name: Update .upptimerc.yml with new sites
        run: |
          # Prendi tutto fino alla riga "sites:"
          awk 'BEGIN{print_header=1} /^sites:/ {print; exit} {print}' .upptimerc.yml > header.yml

          # Prendi tutto dopo la sezione sites
          awk 'found && NF && !/^\s*-/ {print; found=0} /^sites:/ {found=1; next} found && /^\s*-/ {next}' .upptimerc.yml > footer.yml || true

          # Costruisci il nuovo file completo
          cat header.yml > updated_upptimerc.yml
          echo "sites:" >> updated_upptimerc.yml
          cat new_sites_block.yml >> updated_upptimerc.yml
          echo "" >> updated_upptimerc.yml
          cat footer.yml >> updated_upptimerc.yml || true

          # Sovrascrivi il file originale
          mv updated_upptimerc.yml .upptimerc.yml

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .upptimerc.yml
          if git diff --cached --quiet; then
            echo "Nessuna modifica da committare"
          else
            git commit -m "Update sites section in .upptimerc.yml from API"
            git push
          fi
